#!/usr/bin/env node
'use strict';

// Rebuilds public/assets/icons.svg from Lucide (https://lucide.dev, ISC license).
// Usage: npm pack lucide-static && tar -xzf lucide-static-*.tgz
//        node scripts/build-icons.js ./package/icons

const fs = require('fs');
const path = require('path');

const ICONS = [
    'activity', 'arrow-down', 'arrow-down-left', 'arrow-left-right', 'arrow-up', 'arrow-up-right',
    'banknote', 'bitcoin', 'calendar', 'car', 'chart-candlestick', 'chart-line', 'chart-pie', 'check',
    'chevron-down', 'chevron-left', 'chevron-right', 'circle-alert', 'circle-check', 'cloud-off', 'coins',
    'download', 'eye', 'eye-off', 'file-spreadsheet', 'gem', 'hand-coins', 'house', 'info', 'key-round',
    'landmark', 'layout-dashboard', 'log-out', 'medal', 'moon', 'package', 'pencil', 'piggy-bank', 'plus',
    'refresh-cw', 'search', 'settings', 'sparkles', 'star', 'sun', 'table-2', 'trash-2', 'trending-down',
    'trending-up', 'triangle-alert', 'upload', 'wallet', 'x',
];

const source = process.argv[2];
if (!source) {
    console.error('Usage: node scripts/build-icons.js <path-to-lucide-static/icons>');
    process.exit(1);
}

const symbols = ICONS.map((name) => {
    const svg = fs.readFileSync(path.join(source, `${name}.svg`), 'utf8');
    const inner = svg
        .replace(/<!--[\s\S]*?-->/g, '')
        .replace(/^[\s\S]*?<svg[^>]*>/, '')
        .replace(/<\/svg>[\s\S]*$/, '')
        .replace(/\s*\n\s*/g, '')
        .trim();
    return `<symbol id="${name}" viewBox="0 0 24 24">${inner}</symbol>`;
});

const sprite = [
    '<!-- Lucide icons (https://lucide.dev) - ISC License, Copyright (c) Lucide Contributors. Generated by scripts/build-icons.js -->',
    '<svg xmlns="http://www.w3.org/2000/svg">',
    ...symbols,
    '</svg>',
    '',
].join('\n');

const target = path.join(__dirname, '..', 'public', 'assets', 'icons.svg');
fs.writeFileSync(target, sprite);
console.log(`Wrote ${ICONS.length} icons to ${path.relative(process.cwd(), target)}`);
